// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_events.sql

package sqlite

import (
	"context"
	"database/sql"
)

const getAgentEvent = `-- name: GetAgentEvent :one
SELECT event_id, session_id, run_id, turn_id, seq, type, version, occurred_at, payload FROM agent_events
WHERE event_id = ?
`

func (q *Queries) GetAgentEvent(ctx context.Context, eventID string) (AgentEvent, error) {
	row := q.db.QueryRowContext(ctx, getAgentEvent, eventID)
	var i AgentEvent
	err := row.Scan(
		&i.EventID,
		&i.SessionID,
		&i.RunID,
		&i.TurnID,
		&i.Seq,
		&i.Type,
		&i.Version,
		&i.OccurredAt,
		&i.Payload,
	)
	return i, err
}

const insertAgentEvent = `-- name: InsertAgentEvent :one
INSERT INTO agent_events (
    event_id, session_id, run_id, turn_id, seq, type, version, occurred_at, payload
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING event_id, session_id, run_id, turn_id, seq, type, version, occurred_at, payload
`

type InsertAgentEventParams struct {
	EventID    string
	SessionID  string
	RunID      string
	TurnID     sql.NullString
	Seq        int64
	Type       string
	Version    int64
	OccurredAt string
	Payload    string
}

func (q *Queries) InsertAgentEvent(ctx context.Context, arg InsertAgentEventParams) (AgentEvent, error) {
	row := q.db.QueryRowContext(ctx, insertAgentEvent,
		arg.EventID,
		arg.SessionID,
		arg.RunID,
		arg.TurnID,
		arg.Seq,
		arg.Type,
		arg.Version,
		arg.OccurredAt,
		arg.Payload,
	)
	var i AgentEvent
	err := row.Scan(
		&i.EventID,
		&i.SessionID,
		&i.RunID,
		&i.TurnID,
		&i.Seq,
		&i.Type,
		&i.Version,
		&i.OccurredAt,
		&i.Payload,
	)
	return i, err
}

const listSessionEventsAfter = `-- name: ListSessionEventsAfter :many
SELECT event_id, session_id, run_id, turn_id, seq, type, version, occurred_at, payload FROM agent_events
WHERE session_id = ? AND seq > ?
ORDER BY seq
`

type ListSessionEventsAfterParams struct {
	SessionID string
	Seq       int64
}

func (q *Queries) ListSessionEventsAfter(ctx context.Context, arg ListSessionEventsAfterParams) ([]AgentEvent, error) {
	rows, err := q.db.QueryContext(ctx, listSessionEventsAfter, arg.SessionID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentEvent
	for rows.Next() {
		var i AgentEvent
		if err := rows.Scan(
			&i.EventID,
			&i.SessionID,
			&i.RunID,
			&i.TurnID,
			&i.Seq,
			&i.Type,
			&i.Version,
			&i.OccurredAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
