// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approvals.sql

package sqlite

import (
	"context"
)

const countSessionApprovals = `-- name: CountSessionApprovals :one
SELECT COUNT(*) FROM approvals
WHERE session_id = ?
`

func (q *Queries) CountSessionApprovals(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionApprovals, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getApproval = `-- name: GetApproval :one
SELECT id, session_id, run_id, tool_call_id, scope, status, expires_at, tool_calls FROM approvals
WHERE id = ?
`

func (q *Queries) GetApproval(ctx context.Context, id string) (Approval, error) {
	row := q.db.QueryRowContext(ctx, getApproval, id)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RunID,
		&i.ToolCallID,
		&i.Scope,
		&i.Status,
		&i.ExpiresAt,
		&i.ToolCalls,
	)
	return i, err
}

const insertApproval = `-- name: InsertApproval :one
INSERT INTO approvals (
    id, session_id, run_id, tool_call_id, tool_calls, scope, status, expires_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, session_id, run_id, tool_call_id, scope, status, expires_at, tool_calls
`

type InsertApprovalParams struct {
	ID         string
	SessionID  string
	RunID      string
	ToolCallID string
	ToolCalls  string
	Scope      string
	Status     string
	ExpiresAt  string
}

func (q *Queries) InsertApproval(ctx context.Context, arg InsertApprovalParams) (Approval, error) {
	row := q.db.QueryRowContext(ctx, insertApproval,
		arg.ID,
		arg.SessionID,
		arg.RunID,
		arg.ToolCallID,
		arg.ToolCalls,
		arg.Scope,
		arg.Status,
		arg.ExpiresAt,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RunID,
		&i.ToolCallID,
		&i.Scope,
		&i.Status,
		&i.ExpiresAt,
		&i.ToolCalls,
	)
	return i, err
}

const updateApproval = `-- name: UpdateApproval :one
UPDATE approvals
SET scope = ?, status = ?, tool_calls = ?
WHERE id = ?
RETURNING id, session_id, run_id, tool_call_id, scope, status, expires_at, tool_calls
`

type UpdateApprovalParams struct {
	Scope     string
	Status    string
	ToolCalls string
	ID        string
}

func (q *Queries) UpdateApproval(ctx context.Context, arg UpdateApprovalParams) (Approval, error) {
	row := q.db.QueryRowContext(ctx, updateApproval,
		arg.Scope,
		arg.Status,
		arg.ToolCalls,
		arg.ID,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RunID,
		&i.ToolCallID,
		&i.Scope,
		&i.Status,
		&i.ExpiresAt,
		&i.ToolCalls,
	)
	return i, err
}
