// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approvals.sql

package sqlite

import (
	"context"
)

const getApproval = `-- name: GetApproval :one
SELECT id, session_id, run_id, tool_call_id, scope, status, expires_at FROM approvals
WHERE id = ?
`

func (q *Queries) GetApproval(ctx context.Context, id string) (Approval, error) {
	row := q.db.QueryRowContext(ctx, getApproval, id)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RunID,
		&i.ToolCallID,
		&i.Scope,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const insertApproval = `-- name: InsertApproval :one
INSERT INTO approvals (
    id, session_id, run_id, tool_call_id, scope, status, expires_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, session_id, run_id, tool_call_id, scope, status, expires_at
`

type InsertApprovalParams struct {
	ID         string
	SessionID  string
	RunID      string
	ToolCallID string
	Scope      string
	Status     string
	ExpiresAt  string
}

func (q *Queries) InsertApproval(ctx context.Context, arg InsertApprovalParams) (Approval, error) {
	row := q.db.QueryRowContext(ctx, insertApproval,
		arg.ID,
		arg.SessionID,
		arg.RunID,
		arg.ToolCallID,
		arg.Scope,
		arg.Status,
		arg.ExpiresAt,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RunID,
		&i.ToolCallID,
		&i.Scope,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const listSessionApprovals = `-- name: ListSessionApprovals :many
SELECT id, session_id, run_id, tool_call_id, scope, status, expires_at FROM approvals
WHERE session_id = ?
ORDER BY id
`

func (q *Queries) ListSessionApprovals(ctx context.Context, sessionID string) ([]Approval, error) {
	rows, err := q.db.QueryContext(ctx, listSessionApprovals, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Approval
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RunID,
			&i.ToolCallID,
			&i.Scope,
			&i.Status,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApproval = `-- name: UpdateApproval :one
UPDATE approvals
SET scope = ?, status = ?
WHERE id = ?
RETURNING id, session_id, run_id, tool_call_id, scope, status, expires_at
`

type UpdateApprovalParams struct {
	Scope  string
	Status string
	ID     string
}

func (q *Queries) UpdateApproval(ctx context.Context, arg UpdateApprovalParams) (Approval, error) {
	row := q.db.QueryRowContext(ctx, updateApproval, arg.Scope, arg.Status, arg.ID)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RunID,
		&i.ToolCallID,
		&i.Scope,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}
