// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board.sql

package sqlite

import (
	"context"
)

const clearPlacementCheckout = `-- name: ClearPlacementCheckout :exec
UPDATE session_placements
SET checkout = ''
WHERE work_id = ? AND checkout = ?
`

type ClearPlacementCheckoutParams struct {
	WorkID   string
	Checkout string
}

func (q *Queries) ClearPlacementCheckout(ctx context.Context, arg ClearPlacementCheckoutParams) error {
	_, err := q.db.ExecContext(ctx, clearPlacementCheckout, arg.WorkID, arg.Checkout)
	return err
}

const deletePlacementsByWork = `-- name: DeletePlacementsByWork :exec
DELETE FROM session_placements
WHERE work_id = ?
`

func (q *Queries) DeletePlacementsByWork(ctx context.Context, workID string) error {
	_, err := q.db.ExecContext(ctx, deletePlacementsByWork, workID)
	return err
}

const deleteSessionDirectory = `-- name: DeleteSessionDirectory :exec
DELETE FROM session_directories
WHERE engine = ? AND session_id = ?
`

type DeleteSessionDirectoryParams struct {
	Engine    string
	SessionID string
}

func (q *Queries) DeleteSessionDirectory(ctx context.Context, arg DeleteSessionDirectoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteSessionDirectory, arg.Engine, arg.SessionID)
	return err
}

const deleteSessionIssue = `-- name: DeleteSessionIssue :exec
DELETE FROM session_issues
WHERE engine = ? AND session_id = ?
`

type DeleteSessionIssueParams struct {
	Engine    string
	SessionID string
}

func (q *Queries) DeleteSessionIssue(ctx context.Context, arg DeleteSessionIssueParams) error {
	_, err := q.db.ExecContext(ctx, deleteSessionIssue, arg.Engine, arg.SessionID)
	return err
}

const deleteSessionPlacement = `-- name: DeleteSessionPlacement :exec
DELETE FROM session_placements
WHERE engine = ? AND session_id = ?
`

type DeleteSessionPlacementParams struct {
	Engine    string
	SessionID string
}

func (q *Queries) DeleteSessionPlacement(ctx context.Context, arg DeleteSessionPlacementParams) error {
	_, err := q.db.ExecContext(ctx, deleteSessionPlacement, arg.Engine, arg.SessionID)
	return err
}

const deleteSessionPull = `-- name: DeleteSessionPull :exec
DELETE FROM session_pulls
WHERE engine = ? AND session_id = ? AND repo = ? AND number = ?
`

type DeleteSessionPullParams struct {
	Engine    string
	SessionID string
	Repo      string
	Number    int64
}

func (q *Queries) DeleteSessionPull(ctx context.Context, arg DeleteSessionPullParams) error {
	_, err := q.db.ExecContext(ctx, deleteSessionPull,
		arg.Engine,
		arg.SessionID,
		arg.Repo,
		arg.Number,
	)
	return err
}

const deleteSessionPulls = `-- name: DeleteSessionPulls :exec
DELETE FROM session_pulls
WHERE engine = ? AND session_id = ?
`

type DeleteSessionPullsParams struct {
	Engine    string
	SessionID string
}

func (q *Queries) DeleteSessionPulls(ctx context.Context, arg DeleteSessionPullsParams) error {
	_, err := q.db.ExecContext(ctx, deleteSessionPulls, arg.Engine, arg.SessionID)
	return err
}

const deleteWork = `-- name: DeleteWork :exec
DELETE FROM works
WHERE id = ?
`

func (q *Queries) DeleteWork(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWork, id)
	return err
}

const deleteWorkCheckout = `-- name: DeleteWorkCheckout :exec
DELETE FROM work_checkouts
WHERE work_id = ? AND path = ?
`

type DeleteWorkCheckoutParams struct {
	WorkID string
	Path   string
}

func (q *Queries) DeleteWorkCheckout(ctx context.Context, arg DeleteWorkCheckoutParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkCheckout, arg.WorkID, arg.Path)
	return err
}

const deleteWorkCheckouts = `-- name: DeleteWorkCheckouts :exec
DELETE FROM work_checkouts
WHERE work_id = ?
`

func (q *Queries) DeleteWorkCheckouts(ctx context.Context, workID string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkCheckouts, workID)
	return err
}

const deleteWorkInfo = `-- name: DeleteWorkInfo :exec
DELETE FROM work_infos
WHERE work_id = ? AND checkout = ?
`

type DeleteWorkInfoParams struct {
	WorkID   string
	Checkout string
}

func (q *Queries) DeleteWorkInfo(ctx context.Context, arg DeleteWorkInfoParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkInfo, arg.WorkID, arg.Checkout)
	return err
}

const deleteWorkInfos = `-- name: DeleteWorkInfos :exec
DELETE FROM work_infos
WHERE work_id = ?
`

func (q *Queries) DeleteWorkInfos(ctx context.Context, workID string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkInfos, workID)
	return err
}

const getSessionDirectory = `-- name: GetSessionDirectory :one
SELECT engine, session_id, path FROM session_directories
WHERE engine = ? AND session_id = ?
`

type GetSessionDirectoryParams struct {
	Engine    string
	SessionID string
}

func (q *Queries) GetSessionDirectory(ctx context.Context, arg GetSessionDirectoryParams) (SessionDirectory, error) {
	row := q.db.QueryRowContext(ctx, getSessionDirectory, arg.Engine, arg.SessionID)
	var i SessionDirectory
	err := row.Scan(&i.Engine, &i.SessionID, &i.Path)
	return i, err
}

const getSessionIssue = `-- name: GetSessionIssue :one
SELECT engine, session_id, repo, number, title, body, url, state, updated_at FROM session_issues
WHERE engine = ? AND session_id = ?
`

type GetSessionIssueParams struct {
	Engine    string
	SessionID string
}

func (q *Queries) GetSessionIssue(ctx context.Context, arg GetSessionIssueParams) (SessionIssue, error) {
	row := q.db.QueryRowContext(ctx, getSessionIssue, arg.Engine, arg.SessionID)
	var i SessionIssue
	err := row.Scan(
		&i.Engine,
		&i.SessionID,
		&i.Repo,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.Url,
		&i.State,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionPlacement = `-- name: GetSessionPlacement :one
SELECT engine, session_id, work_id, checkout FROM session_placements
WHERE engine = ? AND session_id = ?
`

type GetSessionPlacementParams struct {
	Engine    string
	SessionID string
}

func (q *Queries) GetSessionPlacement(ctx context.Context, arg GetSessionPlacementParams) (SessionPlacement, error) {
	row := q.db.QueryRowContext(ctx, getSessionPlacement, arg.Engine, arg.SessionID)
	var i SessionPlacement
	err := row.Scan(
		&i.Engine,
		&i.SessionID,
		&i.WorkID,
		&i.Checkout,
	)
	return i, err
}

const getWork = `-- name: GetWork :one
SELECT id, tenant_id, user_id, title, created_at, updated_at FROM works
WHERE id = ?
`

func (q *Queries) GetWork(ctx context.Context, id string) (Work, error) {
	row := q.db.QueryRowContext(ctx, getWork, id)
	var i Work
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkCheckout = `-- name: GetWorkCheckout :one
SELECT work_id, path, kind FROM work_checkouts
WHERE work_id = ? AND path = ?
`

type GetWorkCheckoutParams struct {
	WorkID string
	Path   string
}

func (q *Queries) GetWorkCheckout(ctx context.Context, arg GetWorkCheckoutParams) (WorkCheckout, error) {
	row := q.db.QueryRowContext(ctx, getWorkCheckout, arg.WorkID, arg.Path)
	var i WorkCheckout
	err := row.Scan(&i.WorkID, &i.Path, &i.Kind)
	return i, err
}

const getWorkInfo = `-- name: GetWorkInfo :one
SELECT work_id, checkout, body, updated_at FROM work_infos
WHERE work_id = ? AND checkout = ?
`

type GetWorkInfoParams struct {
	WorkID   string
	Checkout string
}

func (q *Queries) GetWorkInfo(ctx context.Context, arg GetWorkInfoParams) (WorkInfo, error) {
	row := q.db.QueryRowContext(ctx, getWorkInfo, arg.WorkID, arg.Checkout)
	var i WorkInfo
	err := row.Scan(
		&i.WorkID,
		&i.Checkout,
		&i.Body,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSessionPlacement = `-- name: InsertSessionPlacement :one
INSERT INTO session_placements (
    engine, session_id, work_id, checkout
) VALUES (
    ?, ?, ?, ?
)
RETURNING engine, session_id, work_id, checkout
`

type InsertSessionPlacementParams struct {
	Engine    string
	SessionID string
	WorkID    string
	Checkout  string
}

func (q *Queries) InsertSessionPlacement(ctx context.Context, arg InsertSessionPlacementParams) (SessionPlacement, error) {
	row := q.db.QueryRowContext(ctx, insertSessionPlacement,
		arg.Engine,
		arg.SessionID,
		arg.WorkID,
		arg.Checkout,
	)
	var i SessionPlacement
	err := row.Scan(
		&i.Engine,
		&i.SessionID,
		&i.WorkID,
		&i.Checkout,
	)
	return i, err
}

const insertWork = `-- name: InsertWork :one
INSERT INTO works (
    id, tenant_id, user_id, title, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, tenant_id, user_id, title, created_at, updated_at
`

type InsertWorkParams struct {
	ID        string
	TenantID  string
	UserID    string
	Title     string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) InsertWork(ctx context.Context, arg InsertWorkParams) (Work, error) {
	row := q.db.QueryRowContext(ctx, insertWork,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Title,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Work
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorkCheckout = `-- name: InsertWorkCheckout :one
INSERT INTO work_checkouts (
    work_id, path, kind
) VALUES (
    ?, ?, ?
)
RETURNING work_id, path, kind
`

type InsertWorkCheckoutParams struct {
	WorkID string
	Path   string
	Kind   string
}

func (q *Queries) InsertWorkCheckout(ctx context.Context, arg InsertWorkCheckoutParams) (WorkCheckout, error) {
	row := q.db.QueryRowContext(ctx, insertWorkCheckout, arg.WorkID, arg.Path, arg.Kind)
	var i WorkCheckout
	err := row.Scan(&i.WorkID, &i.Path, &i.Kind)
	return i, err
}

const listPlacementsByUser = `-- name: ListPlacementsByUser :many
SELECT p.engine, p.session_id, p.work_id, p.checkout
FROM session_placements p
INNER JOIN works w ON w.id = p.work_id
WHERE w.tenant_id = ? AND w.user_id = ?
ORDER BY w.updated_at DESC, p.session_id ASC
`

type ListPlacementsByUserParams struct {
	TenantID string
	UserID   string
}

func (q *Queries) ListPlacementsByUser(ctx context.Context, arg ListPlacementsByUserParams) ([]SessionPlacement, error) {
	rows, err := q.db.QueryContext(ctx, listPlacementsByUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionPlacement
	for rows.Next() {
		var i SessionPlacement
		if err := rows.Scan(
			&i.Engine,
			&i.SessionID,
			&i.WorkID,
			&i.Checkout,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacementsByWork = `-- name: ListPlacementsByWork :many
SELECT engine, session_id, work_id, checkout FROM session_placements
WHERE work_id = ?
ORDER BY session_id ASC
`

func (q *Queries) ListPlacementsByWork(ctx context.Context, workID string) ([]SessionPlacement, error) {
	rows, err := q.db.QueryContext(ctx, listPlacementsByWork, workID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionPlacement
	for rows.Next() {
		var i SessionPlacement
		if err := rows.Scan(
			&i.Engine,
			&i.SessionID,
			&i.WorkID,
			&i.Checkout,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionPulls = `-- name: ListSessionPulls :many
SELECT engine, session_id, repo, number, title, body, url, state, updated_at FROM session_pulls
WHERE engine = ? AND session_id = ?
ORDER BY number ASC
`

type ListSessionPullsParams struct {
	Engine    string
	SessionID string
}

func (q *Queries) ListSessionPulls(ctx context.Context, arg ListSessionPullsParams) ([]SessionPull, error) {
	rows, err := q.db.QueryContext(ctx, listSessionPulls, arg.Engine, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionPull
	for rows.Next() {
		var i SessionPull
		if err := rows.Scan(
			&i.Engine,
			&i.SessionID,
			&i.Repo,
			&i.Number,
			&i.Title,
			&i.Body,
			&i.Url,
			&i.State,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUngroupedNativeSessions = `-- name: ListUngroupedNativeSessions :many
SELECT s.id, s.tenant_id, s.user_id, s.agent_id, s.status, s.active_run_id, s.last_event_seq, s.compaction_seq, s.created_at, s.updated_at, s.workspace_id, s.summary
FROM sessions s
LEFT JOIN session_placements p
    ON p.engine = 'native' AND p.session_id = s.id
WHERE s.tenant_id = ? AND s.user_id = ?
  AND s.status != 'archived'
  AND p.session_id IS NULL
ORDER BY s.updated_at DESC
`

type ListUngroupedNativeSessionsParams struct {
	TenantID string
	UserID   string
}

func (q *Queries) ListUngroupedNativeSessions(ctx context.Context, arg ListUngroupedNativeSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listUngroupedNativeSessions, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.AgentID,
			&i.Status,
			&i.ActiveRunID,
			&i.LastEventSeq,
			&i.CompactionSeq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceID,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkCheckouts = `-- name: ListWorkCheckouts :many
SELECT work_id, path, kind FROM work_checkouts
WHERE work_id = ?
ORDER BY path ASC
`

func (q *Queries) ListWorkCheckouts(ctx context.Context, workID string) ([]WorkCheckout, error) {
	rows, err := q.db.QueryContext(ctx, listWorkCheckouts, workID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkCheckout
	for rows.Next() {
		var i WorkCheckout
		if err := rows.Scan(&i.WorkID, &i.Path, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkInfos = `-- name: ListWorkInfos :many
SELECT work_id, checkout, body, updated_at FROM work_infos
WHERE work_id = ?
`

func (q *Queries) ListWorkInfos(ctx context.Context, workID string) ([]WorkInfo, error) {
	rows, err := q.db.QueryContext(ctx, listWorkInfos, workID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkInfo
	for rows.Next() {
		var i WorkInfo
		if err := rows.Scan(
			&i.WorkID,
			&i.Checkout,
			&i.Body,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorksByUser = `-- name: ListWorksByUser :many
SELECT id, tenant_id, user_id, title, created_at, updated_at FROM works
WHERE tenant_id = ? AND user_id = ?
ORDER BY updated_at DESC
`

type ListWorksByUserParams struct {
	TenantID string
	UserID   string
}

func (q *Queries) ListWorksByUser(ctx context.Context, arg ListWorksByUserParams) ([]Work, error) {
	rows, err := q.db.QueryContext(ctx, listWorksByUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Work
	for rows.Next() {
		var i Work
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchWork = `-- name: TouchWork :exec
UPDATE works
SET updated_at = ?
WHERE id = ?
`

type TouchWorkParams struct {
	UpdatedAt string
	ID        string
}

func (q *Queries) TouchWork(ctx context.Context, arg TouchWorkParams) error {
	_, err := q.db.ExecContext(ctx, touchWork, arg.UpdatedAt, arg.ID)
	return err
}

const updateSessionPlacement = `-- name: UpdateSessionPlacement :one
UPDATE session_placements
SET work_id = ?, checkout = ?
WHERE engine = ? AND session_id = ?
RETURNING engine, session_id, work_id, checkout
`

type UpdateSessionPlacementParams struct {
	WorkID    string
	Checkout  string
	Engine    string
	SessionID string
}

func (q *Queries) UpdateSessionPlacement(ctx context.Context, arg UpdateSessionPlacementParams) (SessionPlacement, error) {
	row := q.db.QueryRowContext(ctx, updateSessionPlacement,
		arg.WorkID,
		arg.Checkout,
		arg.Engine,
		arg.SessionID,
	)
	var i SessionPlacement
	err := row.Scan(
		&i.Engine,
		&i.SessionID,
		&i.WorkID,
		&i.Checkout,
	)
	return i, err
}

const updateWork = `-- name: UpdateWork :one
UPDATE works
SET title = ?, updated_at = ?
WHERE id = ?
RETURNING id, tenant_id, user_id, title, created_at, updated_at
`

type UpdateWorkParams struct {
	Title     string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateWork(ctx context.Context, arg UpdateWorkParams) (Work, error) {
	row := q.db.QueryRowContext(ctx, updateWork, arg.Title, arg.UpdatedAt, arg.ID)
	var i Work
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSessionDirectory = `-- name: UpsertSessionDirectory :one
INSERT INTO session_directories (
    engine, session_id, path
) VALUES (
    ?, ?, ?
)
ON CONFLICT (engine, session_id) DO UPDATE SET
    path = excluded.path
RETURNING engine, session_id, path
`

type UpsertSessionDirectoryParams struct {
	Engine    string
	SessionID string
	Path      string
}

func (q *Queries) UpsertSessionDirectory(ctx context.Context, arg UpsertSessionDirectoryParams) (SessionDirectory, error) {
	row := q.db.QueryRowContext(ctx, upsertSessionDirectory, arg.Engine, arg.SessionID, arg.Path)
	var i SessionDirectory
	err := row.Scan(&i.Engine, &i.SessionID, &i.Path)
	return i, err
}

const upsertSessionIssue = `-- name: UpsertSessionIssue :one
INSERT INTO session_issues (
    engine, session_id, repo, number, title, body, url, state, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT (engine, session_id) DO UPDATE SET
    repo = excluded.repo,
    number = excluded.number,
    title = excluded.title,
    body = excluded.body,
    url = excluded.url,
    state = excluded.state,
    updated_at = excluded.updated_at
RETURNING engine, session_id, repo, number, title, body, url, state, updated_at
`

type UpsertSessionIssueParams struct {
	Engine    string
	SessionID string
	Repo      string
	Number    int64
	Title     string
	Body      string
	Url       string
	State     string
	UpdatedAt string
}

func (q *Queries) UpsertSessionIssue(ctx context.Context, arg UpsertSessionIssueParams) (SessionIssue, error) {
	row := q.db.QueryRowContext(ctx, upsertSessionIssue,
		arg.Engine,
		arg.SessionID,
		arg.Repo,
		arg.Number,
		arg.Title,
		arg.Body,
		arg.Url,
		arg.State,
		arg.UpdatedAt,
	)
	var i SessionIssue
	err := row.Scan(
		&i.Engine,
		&i.SessionID,
		&i.Repo,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.Url,
		&i.State,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSessionPull = `-- name: UpsertSessionPull :one
INSERT INTO session_pulls (
    engine, session_id, repo, number, title, body, url, state, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT (engine, session_id, repo, number) DO UPDATE SET
    title = excluded.title,
    body = excluded.body,
    url = excluded.url,
    state = excluded.state,
    updated_at = excluded.updated_at
RETURNING engine, session_id, repo, number, title, body, url, state, updated_at
`

type UpsertSessionPullParams struct {
	Engine    string
	SessionID string
	Repo      string
	Number    int64
	Title     string
	Body      string
	Url       string
	State     string
	UpdatedAt string
}

func (q *Queries) UpsertSessionPull(ctx context.Context, arg UpsertSessionPullParams) (SessionPull, error) {
	row := q.db.QueryRowContext(ctx, upsertSessionPull,
		arg.Engine,
		arg.SessionID,
		arg.Repo,
		arg.Number,
		arg.Title,
		arg.Body,
		arg.Url,
		arg.State,
		arg.UpdatedAt,
	)
	var i SessionPull
	err := row.Scan(
		&i.Engine,
		&i.SessionID,
		&i.Repo,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.Url,
		&i.State,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkInfo = `-- name: UpsertWorkInfo :one
INSERT INTO work_infos (
    work_id, checkout, body, updated_at
) VALUES (
    ?, ?, ?, ?
)
ON CONFLICT (work_id, checkout) DO UPDATE SET
    body = excluded.body,
    updated_at = excluded.updated_at
RETURNING work_id, checkout, body, updated_at
`

type UpsertWorkInfoParams struct {
	WorkID    string
	Checkout  string
	Body      string
	UpdatedAt string
}

func (q *Queries) UpsertWorkInfo(ctx context.Context, arg UpsertWorkInfoParams) (WorkInfo, error) {
	row := q.db.QueryRowContext(ctx, upsertWorkInfo,
		arg.WorkID,
		arg.Checkout,
		arg.Body,
		arg.UpdatedAt,
	)
	var i WorkInfo
	err := row.Scan(
		&i.WorkID,
		&i.Checkout,
		&i.Body,
		&i.UpdatedAt,
	)
	return i, err
}
