// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compaction_checkpoints.sql

package sqlite

import (
	"context"
)

const getCompactionCheckpoint = `-- name: GetCompactionCheckpoint :one
SELECT id, session_id, base_event_seq, summary, created_by_run, created_at FROM compaction_checkpoints
WHERE id = ?
`

func (q *Queries) GetCompactionCheckpoint(ctx context.Context, id string) (CompactionCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, getCompactionCheckpoint, id)
	var i CompactionCheckpoint
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.BaseEventSeq,
		&i.Summary,
		&i.CreatedByRun,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestCheckpoint = `-- name: GetLatestCheckpoint :one
SELECT id, session_id, base_event_seq, summary, created_by_run, created_at FROM compaction_checkpoints
WHERE session_id = ?
ORDER BY base_event_seq DESC
LIMIT 1
`

func (q *Queries) GetLatestCheckpoint(ctx context.Context, sessionID string) (CompactionCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, getLatestCheckpoint, sessionID)
	var i CompactionCheckpoint
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.BaseEventSeq,
		&i.Summary,
		&i.CreatedByRun,
		&i.CreatedAt,
	)
	return i, err
}

const insertCompactionCheckpoint = `-- name: InsertCompactionCheckpoint :one
INSERT INTO compaction_checkpoints (
    id, session_id, base_event_seq, summary, created_by_run, created_at
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, session_id, base_event_seq, summary, created_by_run, created_at
`

type InsertCompactionCheckpointParams struct {
	ID           string
	SessionID    string
	BaseEventSeq int64
	Summary      string
	CreatedByRun string
	CreatedAt    string
}

func (q *Queries) InsertCompactionCheckpoint(ctx context.Context, arg InsertCompactionCheckpointParams) (CompactionCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, insertCompactionCheckpoint,
		arg.ID,
		arg.SessionID,
		arg.BaseEventSeq,
		arg.Summary,
		arg.CreatedByRun,
		arg.CreatedAt,
	)
	var i CompactionCheckpoint
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.BaseEventSeq,
		&i.Summary,
		&i.CreatedByRun,
		&i.CreatedAt,
	)
	return i, err
}
