// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: context_messages.sql

package sqlite

import (
	"context"
)

const insertContextMessage = `-- name: InsertContextMessage :one
INSERT INTO context_messages (
    id, workspace_id, session_id, run_id, role, content, created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(id) DO UPDATE SET
    workspace_id = excluded.workspace_id,
    session_id = excluded.session_id,
    run_id = excluded.run_id,
    role = excluded.role,
    content = excluded.content,
    created_at = excluded.created_at
RETURNING id, workspace_id, session_id, run_id, role, content, created_at
`

type InsertContextMessageParams struct {
	ID          string
	WorkspaceID string
	SessionID   string
	RunID       string
	Role        string
	Content     string
	CreatedAt   string
}

func (q *Queries) InsertContextMessage(ctx context.Context, arg InsertContextMessageParams) (ContextMessage, error) {
	row := q.db.QueryRowContext(ctx, insertContextMessage,
		arg.ID,
		arg.WorkspaceID,
		arg.SessionID,
		arg.RunID,
		arg.Role,
		arg.Content,
		arg.CreatedAt,
	)
	var i ContextMessage
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SessionID,
		&i.RunID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
