// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlite

import (
	"context"
	"database/sql"
)

const countSessionMessages = `-- name: CountSessionMessages :one
SELECT COUNT(*) FROM messages
WHERE session_id = ?
`

func (q *Queries) CountSessionMessages(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionMessages, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = ?
`

func (q *Queries) DeleteMessage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, id)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, session_id, run_id, turn_id, role, content, attachments, tool_calls, event_seq, created_at FROM messages
WHERE id = ?
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RunID,
		&i.TurnID,
		&i.Role,
		&i.Content,
		&i.Attachments,
		&i.ToolCalls,
		&i.EventSeq,
		&i.CreatedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (
    id, session_id, run_id, turn_id, role, content, attachments, tool_calls, event_seq, created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, session_id, run_id, turn_id, role, content, attachments, tool_calls, event_seq, created_at
`

type InsertMessageParams struct {
	ID          string
	SessionID   string
	RunID       sql.NullString
	TurnID      sql.NullString
	Role        string
	Content     string
	Attachments sql.NullString
	ToolCalls   sql.NullString
	EventSeq    int64
	CreatedAt   string
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, insertMessage,
		arg.ID,
		arg.SessionID,
		arg.RunID,
		arg.TurnID,
		arg.Role,
		arg.Content,
		arg.Attachments,
		arg.ToolCalls,
		arg.EventSeq,
		arg.CreatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RunID,
		&i.TurnID,
		&i.Role,
		&i.Content,
		&i.Attachments,
		&i.ToolCalls,
		&i.EventSeq,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesAfterSeq = `-- name: ListMessagesAfterSeq :many
SELECT id, session_id, run_id, turn_id, role, content, attachments, tool_calls, event_seq, created_at FROM messages
WHERE session_id = ? AND event_seq > ?
ORDER BY event_seq, created_at
`

type ListMessagesAfterSeqParams struct {
	SessionID string
	EventSeq  int64
}

func (q *Queries) ListMessagesAfterSeq(ctx context.Context, arg ListMessagesAfterSeqParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesAfterSeq, arg.SessionID, arg.EventSeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RunID,
			&i.TurnID,
			&i.Role,
			&i.Content,
			&i.Attachments,
			&i.ToolCalls,
			&i.EventSeq,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionMessages = `-- name: ListSessionMessages :many
SELECT id, session_id, run_id, turn_id, role, content, attachments, tool_calls, event_seq, created_at FROM messages
WHERE session_id = ?
ORDER BY event_seq, created_at
`

func (q *Queries) ListSessionMessages(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listSessionMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RunID,
			&i.TurnID,
			&i.Role,
			&i.Content,
			&i.Attachments,
			&i.ToolCalls,
			&i.EventSeq,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
