// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run_overlays.sql

package sqlite

import (
	"context"
)

const getRunOverlay = `-- name: GetRunOverlay :one
SELECT run_id, system_prompt, hidden, updated_at FROM run_overlays
WHERE run_id = ?
`

func (q *Queries) GetRunOverlay(ctx context.Context, runID string) (RunOverlay, error) {
	row := q.db.QueryRowContext(ctx, getRunOverlay, runID)
	var i RunOverlay
	err := row.Scan(
		&i.RunID,
		&i.SystemPrompt,
		&i.Hidden,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRunOverlay = `-- name: UpsertRunOverlay :one
INSERT INTO run_overlays (
    run_id, system_prompt, hidden, updated_at
) VALUES (
    ?, ?, ?, ?
)
ON CONFLICT(run_id) DO UPDATE SET
    system_prompt = excluded.system_prompt,
    hidden = excluded.hidden,
    updated_at = excluded.updated_at
RETURNING run_id, system_prompt, hidden, updated_at
`

type UpsertRunOverlayParams struct {
	RunID        string
	SystemPrompt string
	Hidden       string
	UpdatedAt    string
}

func (q *Queries) UpsertRunOverlay(ctx context.Context, arg UpsertRunOverlayParams) (RunOverlay, error) {
	row := q.db.QueryRowContext(ctx, upsertRunOverlay,
		arg.RunID,
		arg.SystemPrompt,
		arg.Hidden,
		arg.UpdatedAt,
	)
	var i RunOverlay
	err := row.Scan(
		&i.RunID,
		&i.SystemPrompt,
		&i.Hidden,
		&i.UpdatedAt,
	)
	return i, err
}
