// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run_tool_checkpoints.sql

package sqlite

import (
	"context"
)

const deleteRunToolCheckpoint = `-- name: DeleteRunToolCheckpoint :exec
DELETE FROM run_tool_checkpoints
WHERE run_id = ?
`

func (q *Queries) DeleteRunToolCheckpoint(ctx context.Context, runID string) error {
	_, err := q.db.ExecContext(ctx, deleteRunToolCheckpoint, runID)
	return err
}

const getRunToolCheckpoint = `-- name: GetRunToolCheckpoint :one
SELECT run_id, turn_id, completed_calls, pending_calls, results, updated_at, approved_calls, denied_calls FROM run_tool_checkpoints
WHERE run_id = ?
`

func (q *Queries) GetRunToolCheckpoint(ctx context.Context, runID string) (RunToolCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, getRunToolCheckpoint, runID)
	var i RunToolCheckpoint
	err := row.Scan(
		&i.RunID,
		&i.TurnID,
		&i.CompletedCalls,
		&i.PendingCalls,
		&i.Results,
		&i.UpdatedAt,
		&i.ApprovedCalls,
		&i.DeniedCalls,
	)
	return i, err
}

const upsertRunToolCheckpoint = `-- name: UpsertRunToolCheckpoint :one
INSERT INTO run_tool_checkpoints (
    run_id, turn_id, completed_calls, pending_calls, results, approved_calls, denied_calls, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(run_id) DO UPDATE SET
    turn_id = excluded.turn_id,
    completed_calls = excluded.completed_calls,
    pending_calls = excluded.pending_calls,
    results = excluded.results,
    approved_calls = excluded.approved_calls,
    denied_calls = excluded.denied_calls,
    updated_at = excluded.updated_at
RETURNING run_id, turn_id, completed_calls, pending_calls, results, updated_at, approved_calls, denied_calls
`

type UpsertRunToolCheckpointParams struct {
	RunID          string
	TurnID         string
	CompletedCalls string
	PendingCalls   string
	Results        string
	ApprovedCalls  string
	DeniedCalls    string
	UpdatedAt      string
}

func (q *Queries) UpsertRunToolCheckpoint(ctx context.Context, arg UpsertRunToolCheckpointParams) (RunToolCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, upsertRunToolCheckpoint,
		arg.RunID,
		arg.TurnID,
		arg.CompletedCalls,
		arg.PendingCalls,
		arg.Results,
		arg.ApprovedCalls,
		arg.DeniedCalls,
		arg.UpdatedAt,
	)
	var i RunToolCheckpoint
	err := row.Scan(
		&i.RunID,
		&i.TurnID,
		&i.CompletedCalls,
		&i.PendingCalls,
		&i.Results,
		&i.UpdatedAt,
		&i.ApprovedCalls,
		&i.DeniedCalls,
	)
	return i, err
}
