// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run_harness.sql

package sqlite

import (
	"context"
	"database/sql"
)

const getRunHarness = `-- name: GetRunHarness :one
SELECT snapshot_oid, harness FROM runs
WHERE id = ?
`

type GetRunHarnessRow struct {
	SnapshotOid sql.NullString
	Harness     string
}

func (q *Queries) GetRunHarness(ctx context.Context, id string) (GetRunHarnessRow, error) {
	row := q.db.QueryRowContext(ctx, getRunHarness, id)
	var i GetRunHarnessRow
	err := row.Scan(&i.SnapshotOid, &i.Harness)
	return i, err
}

const updateRunHarness = `-- name: UpdateRunHarness :exec
UPDATE runs
SET snapshot_oid = ?, harness = ?
WHERE id = ?
`

type UpdateRunHarnessParams struct {
	SnapshotOid sql.NullString
	Harness     string
	ID          string
}

func (q *Queries) UpdateRunHarness(ctx context.Context, arg UpdateRunHarnessParams) error {
	_, err := q.db.ExecContext(ctx, updateRunHarness, arg.SnapshotOid, arg.Harness, arg.ID)
	return err
}
