// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package sqlite

import (
	"context"
	"database/sql"
)

const getRun = `-- name: GetRun :one
SELECT id, session_id, trigger_message_id, mode, config, status, current_turn_id, stop_reason, cancel_requested, started_at, finished_at FROM runs
WHERE id = ?
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TriggerMessageID,
		&i.Mode,
		&i.Config,
		&i.Status,
		&i.CurrentTurnID,
		&i.StopReason,
		&i.CancelRequested,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertRun = `-- name: InsertRun :one
INSERT INTO runs (
    id, session_id, trigger_message_id, mode, config, status, current_turn_id, stop_reason, cancel_requested, started_at, finished_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, session_id, trigger_message_id, mode, config, status, current_turn_id, stop_reason, cancel_requested, started_at, finished_at
`

type InsertRunParams struct {
	ID               string
	SessionID        string
	TriggerMessageID string
	Mode             string
	Config           string
	Status           string
	CurrentTurnID    sql.NullString
	StopReason       sql.NullString
	CancelRequested  int64
	StartedAt        sql.NullString
	FinishedAt       sql.NullString
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, insertRun,
		arg.ID,
		arg.SessionID,
		arg.TriggerMessageID,
		arg.Mode,
		arg.Config,
		arg.Status,
		arg.CurrentTurnID,
		arg.StopReason,
		arg.CancelRequested,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TriggerMessageID,
		&i.Mode,
		&i.Config,
		&i.Status,
		&i.CurrentTurnID,
		&i.StopReason,
		&i.CancelRequested,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listQueuedRuns = `-- name: ListQueuedRuns :many
SELECT id, session_id, trigger_message_id, mode, config, status, current_turn_id, stop_reason, cancel_requested, started_at, finished_at FROM runs
WHERE session_id = ? AND status = 'queued'
ORDER BY id
LIMIT 1
`

func (q *Queries) ListQueuedRuns(ctx context.Context, sessionID string) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listQueuedRuns, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TriggerMessageID,
			&i.Mode,
			&i.Config,
			&i.Status,
			&i.CurrentTurnID,
			&i.StopReason,
			&i.CancelRequested,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecoverableRuns = `-- name: ListRecoverableRuns :many
SELECT id, session_id, trigger_message_id, mode, config, status, current_turn_id, stop_reason, cancel_requested, started_at, finished_at FROM runs
WHERE status IN ('queued', 'loading_context', 'running_llm', 'executing_tools')
ORDER BY id
`

func (q *Queries) ListRecoverableRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRecoverableRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TriggerMessageID,
			&i.Mode,
			&i.Config,
			&i.Status,
			&i.CurrentTurnID,
			&i.StopReason,
			&i.CancelRequested,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionRuns = `-- name: ListSessionRuns :many
SELECT id, session_id, trigger_message_id, mode, config, status, current_turn_id, stop_reason, cancel_requested, started_at, finished_at FROM runs
WHERE session_id = ?
ORDER BY id
`

func (q *Queries) ListSessionRuns(ctx context.Context, sessionID string) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listSessionRuns, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TriggerMessageID,
			&i.Mode,
			&i.Config,
			&i.Status,
			&i.CurrentTurnID,
			&i.StopReason,
			&i.CancelRequested,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaitingApprovalRuns = `-- name: ListWaitingApprovalRuns :many
SELECT id, session_id, trigger_message_id, mode, config, status, current_turn_id, stop_reason, cancel_requested, started_at, finished_at FROM runs
WHERE status = 'waiting_approval'
ORDER BY id
`

func (q *Queries) ListWaitingApprovalRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listWaitingApprovalRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TriggerMessageID,
			&i.Mode,
			&i.Config,
			&i.Status,
			&i.CurrentTurnID,
			&i.StopReason,
			&i.CancelRequested,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRun = `-- name: UpdateRun :one
UPDATE runs
SET status = ?, current_turn_id = ?, stop_reason = ?, cancel_requested = ?, started_at = ?, finished_at = ?
WHERE id = ?
RETURNING id, session_id, trigger_message_id, mode, config, status, current_turn_id, stop_reason, cancel_requested, started_at, finished_at
`

type UpdateRunParams struct {
	Status          string
	CurrentTurnID   sql.NullString
	StopReason      sql.NullString
	CancelRequested int64
	StartedAt       sql.NullString
	FinishedAt      sql.NullString
	ID              string
}

func (q *Queries) UpdateRun(ctx context.Context, arg UpdateRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, updateRun,
		arg.Status,
		arg.CurrentTurnID,
		arg.StopReason,
		arg.CancelRequested,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TriggerMessageID,
		&i.Mode,
		&i.Config,
		&i.Status,
		&i.CurrentTurnID,
		&i.StopReason,
		&i.CancelRequested,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
