// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schema_migrations.sql

package sqlite

import (
	"context"
)

const listSchemaMigrations = `-- name: ListSchemaMigrations :many
SELECT version, applied_at
FROM schema_migrations
ORDER BY version
`

func (q *Queries) ListSchemaMigrations(ctx context.Context) ([]SchemaMigration, error) {
	rows, err := q.db.QueryContext(ctx, listSchemaMigrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchemaMigration
	for rows.Next() {
		var i SchemaMigration
		if err := rows.Scan(&i.Version, &i.AppliedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
