// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_leases.sql

package sqlite

import (
	"context"
)

const deleteSessionLease = `-- name: DeleteSessionLease :exec
DELETE FROM session_leases
WHERE session_id = ?
`

func (q *Queries) DeleteSessionLease(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionLease, sessionID)
	return err
}

const getSessionLease = `-- name: GetSessionLease :one
SELECT session_id, run_id, owner, fencing_token, heartbeat_at, expires_at FROM session_leases
WHERE session_id = ?
`

func (q *Queries) GetSessionLease(ctx context.Context, sessionID string) (SessionLease, error) {
	row := q.db.QueryRowContext(ctx, getSessionLease, sessionID)
	var i SessionLease
	err := row.Scan(
		&i.SessionID,
		&i.RunID,
		&i.Owner,
		&i.FencingToken,
		&i.HeartbeatAt,
		&i.ExpiresAt,
	)
	return i, err
}

const upsertSessionLease = `-- name: UpsertSessionLease :one
INSERT INTO session_leases (
    session_id, run_id, owner, fencing_token, heartbeat_at, expires_at
) VALUES (
    ?, ?, ?, ?, ?, ?
)
ON CONFLICT(session_id) DO UPDATE SET
    run_id = excluded.run_id,
    owner = excluded.owner,
    fencing_token = excluded.fencing_token,
    heartbeat_at = excluded.heartbeat_at,
    expires_at = excluded.expires_at
RETURNING session_id, run_id, owner, fencing_token, heartbeat_at, expires_at
`

type UpsertSessionLeaseParams struct {
	SessionID    string
	RunID        string
	Owner        string
	FencingToken int64
	HeartbeatAt  string
	ExpiresAt    string
}

func (q *Queries) UpsertSessionLease(ctx context.Context, arg UpsertSessionLeaseParams) (SessionLease, error) {
	row := q.db.QueryRowContext(ctx, upsertSessionLease,
		arg.SessionID,
		arg.RunID,
		arg.Owner,
		arg.FencingToken,
		arg.HeartbeatAt,
		arg.ExpiresAt,
	)
	var i SessionLease
	err := row.Scan(
		&i.SessionID,
		&i.RunID,
		&i.Owner,
		&i.FencingToken,
		&i.HeartbeatAt,
		&i.ExpiresAt,
	)
	return i, err
}
