// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: step_jobs.sql

package sqlite

import (
	"context"
)

const cancelOpenStepJobs = `-- name: CancelOpenStepJobs :exec
UPDATE step_jobs
SET status = 'cancelled', updated_at = ?
WHERE run_id = ? AND status IN ('queued', 'running')
`

type CancelOpenStepJobsParams struct {
	UpdatedAt string
	RunID     string
}

func (q *Queries) CancelOpenStepJobs(ctx context.Context, arg CancelOpenStepJobsParams) error {
	_, err := q.db.ExecContext(ctx, cancelOpenStepJobs, arg.UpdatedAt, arg.RunID)
	return err
}

const getLatestOpenStepJob = `-- name: GetLatestOpenStepJob :one
SELECT run_id, step_index, phase, payload, status, attempt, created_at, updated_at FROM step_jobs
WHERE run_id = ? AND status IN ('queued', 'running')
ORDER BY step_index DESC
LIMIT 1
`

func (q *Queries) GetLatestOpenStepJob(ctx context.Context, runID string) (StepJob, error) {
	row := q.db.QueryRowContext(ctx, getLatestOpenStepJob, runID)
	var i StepJob
	err := row.Scan(
		&i.RunID,
		&i.StepIndex,
		&i.Phase,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStepJob = `-- name: GetStepJob :one
SELECT run_id, step_index, phase, payload, status, attempt, created_at, updated_at FROM step_jobs
WHERE run_id = ? AND step_index = ?
`

type GetStepJobParams struct {
	RunID     string
	StepIndex int64
}

func (q *Queries) GetStepJob(ctx context.Context, arg GetStepJobParams) (StepJob, error) {
	row := q.db.QueryRowContext(ctx, getStepJob, arg.RunID, arg.StepIndex)
	var i StepJob
	err := row.Scan(
		&i.RunID,
		&i.StepIndex,
		&i.Phase,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStepJobStatus = `-- name: UpdateStepJobStatus :exec
UPDATE step_jobs
SET status = ?, updated_at = ?
WHERE run_id = ? AND step_index = ?
`

type UpdateStepJobStatusParams struct {
	Status    string
	UpdatedAt string
	RunID     string
	StepIndex int64
}

func (q *Queries) UpdateStepJobStatus(ctx context.Context, arg UpdateStepJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateStepJobStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.RunID,
		arg.StepIndex,
	)
	return err
}

const upsertStepJob = `-- name: UpsertStepJob :one
INSERT INTO step_jobs (
    run_id, step_index, phase, payload, status, attempt, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(run_id, step_index) DO UPDATE SET
    phase = excluded.phase,
    payload = excluded.payload,
    status = excluded.status,
    attempt = excluded.attempt,
    updated_at = excluded.updated_at
RETURNING run_id, step_index, phase, payload, status, attempt, created_at, updated_at
`

type UpsertStepJobParams struct {
	RunID     string
	StepIndex int64
	Phase     string
	Payload   string
	Status    string
	Attempt   int64
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) UpsertStepJob(ctx context.Context, arg UpsertStepJobParams) (StepJob, error) {
	row := q.db.QueryRowContext(ctx, upsertStepJob,
		arg.RunID,
		arg.StepIndex,
		arg.Phase,
		arg.Payload,
		arg.Status,
		arg.Attempt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i StepJob
	err := row.Scan(
		&i.RunID,
		&i.StepIndex,
		&i.Phase,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
