// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: text_memories.sql

package sqlite

import (
	"context"
)

const deleteTextMemory = `-- name: DeleteTextMemory :exec
DELETE FROM text_memories
WHERE scope = ? AND scope_id = ?
`

type DeleteTextMemoryParams struct {
	Scope   string
	ScopeID string
}

func (q *Queries) DeleteTextMemory(ctx context.Context, arg DeleteTextMemoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteTextMemory, arg.Scope, arg.ScopeID)
	return err
}

const getTextMemory = `-- name: GetTextMemory :one
SELECT id, scope, scope_id, content, byte_len, created_at, updated_at FROM text_memories
WHERE scope = ? AND scope_id = ?
`

type GetTextMemoryParams struct {
	Scope   string
	ScopeID string
}

func (q *Queries) GetTextMemory(ctx context.Context, arg GetTextMemoryParams) (TextMemory, error) {
	row := q.db.QueryRowContext(ctx, getTextMemory, arg.Scope, arg.ScopeID)
	var i TextMemory
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.Content,
		&i.ByteLen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTextMemory = `-- name: InsertTextMemory :one
INSERT INTO text_memories (
    id, scope, scope_id, content, byte_len, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, scope, scope_id, content, byte_len, created_at, updated_at
`

type InsertTextMemoryParams struct {
	ID        string
	Scope     string
	ScopeID   string
	Content   string
	ByteLen   int64
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) InsertTextMemory(ctx context.Context, arg InsertTextMemoryParams) (TextMemory, error) {
	row := q.db.QueryRowContext(ctx, insertTextMemory,
		arg.ID,
		arg.Scope,
		arg.ScopeID,
		arg.Content,
		arg.ByteLen,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TextMemory
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.Content,
		&i.ByteLen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTextMemories = `-- name: ListTextMemories :many
SELECT id, scope, scope_id, content, byte_len, created_at, updated_at FROM text_memories
ORDER BY updated_at DESC
`

func (q *Queries) ListTextMemories(ctx context.Context) ([]TextMemory, error) {
	rows, err := q.db.QueryContext(ctx, listTextMemories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TextMemory
	for rows.Next() {
		var i TextMemory
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ScopeID,
			&i.Content,
			&i.ByteLen,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTextMemory = `-- name: UpdateTextMemory :one
UPDATE text_memories
SET content = ?, byte_len = ?, updated_at = ?
WHERE scope = ? AND scope_id = ?
RETURNING id, scope, scope_id, content, byte_len, created_at, updated_at
`

type UpdateTextMemoryParams struct {
	Content   string
	ByteLen   int64
	UpdatedAt string
	Scope     string
	ScopeID   string
}

func (q *Queries) UpdateTextMemory(ctx context.Context, arg UpdateTextMemoryParams) (TextMemory, error) {
	row := q.db.QueryRowContext(ctx, updateTextMemory,
		arg.Content,
		arg.ByteLen,
		arg.UpdatedAt,
		arg.Scope,
		arg.ScopeID,
	)
	var i TextMemory
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.Content,
		&i.ByteLen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
