// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: text_memories.sql

package sqlite

import (
	"context"
)

const deleteTextMemory = `-- name: DeleteTextMemory :exec
DELETE FROM text_memories
WHERE scope = ? AND scope_id = ? AND kind = ? AND name = ?
`

type DeleteTextMemoryParams struct {
	Scope   string
	ScopeID string
	Kind    string
	Name    string
}

func (q *Queries) DeleteTextMemory(ctx context.Context, arg DeleteTextMemoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteTextMemory,
		arg.Scope,
		arg.ScopeID,
		arg.Kind,
		arg.Name,
	)
	return err
}

const getTextMemory = `-- name: GetTextMemory :one
SELECT id, scope, scope_id, content, byte_len, created_at, updated_at, kind, name FROM text_memories
WHERE scope = ? AND scope_id = ? AND kind = ? AND name = ?
`

type GetTextMemoryParams struct {
	Scope   string
	ScopeID string
	Kind    string
	Name    string
}

func (q *Queries) GetTextMemory(ctx context.Context, arg GetTextMemoryParams) (TextMemory, error) {
	row := q.db.QueryRowContext(ctx, getTextMemory,
		arg.Scope,
		arg.ScopeID,
		arg.Kind,
		arg.Name,
	)
	var i TextMemory
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.Content,
		&i.ByteLen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.Name,
	)
	return i, err
}

const listTextMemories = `-- name: ListTextMemories :many
SELECT id, scope, scope_id, content, byte_len, created_at, updated_at, kind, name FROM text_memories
WHERE scope = ? AND scope_id = ?
ORDER BY kind ASC, name ASC
`

type ListTextMemoriesParams struct {
	Scope   string
	ScopeID string
}

func (q *Queries) ListTextMemories(ctx context.Context, arg ListTextMemoriesParams) ([]TextMemory, error) {
	rows, err := q.db.QueryContext(ctx, listTextMemories, arg.Scope, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TextMemory
	for rows.Next() {
		var i TextMemory
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ScopeID,
			&i.Content,
			&i.ByteLen,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kind,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTextMemory = `-- name: UpsertTextMemory :one
INSERT INTO text_memories (
    id, scope, scope_id, kind, name, content, byte_len, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT (scope, scope_id, kind, name) DO UPDATE SET
    content = excluded.content,
    byte_len = excluded.byte_len,
    updated_at = excluded.updated_at
RETURNING id, scope, scope_id, content, byte_len, created_at, updated_at, kind, name
`

type UpsertTextMemoryParams struct {
	ID        string
	Scope     string
	ScopeID   string
	Kind      string
	Name      string
	Content   string
	ByteLen   int64
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) UpsertTextMemory(ctx context.Context, arg UpsertTextMemoryParams) (TextMemory, error) {
	row := q.db.QueryRowContext(ctx, upsertTextMemory,
		arg.ID,
		arg.Scope,
		arg.ScopeID,
		arg.Kind,
		arg.Name,
		arg.Content,
		arg.ByteLen,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TextMemory
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.Content,
		&i.ByteLen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.Name,
	)
	return i, err
}
