// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: turns.sql

package sqlite

import (
	"context"
	"database/sql"
)

const getTurn = `-- name: GetTurn :one
SELECT id, run_id, number, status, first_event_seq, last_event_seq, assistant_msg_id, usage_id, started_at, finished_at FROM turns
WHERE id = ?
`

func (q *Queries) GetTurn(ctx context.Context, id string) (Turn, error) {
	row := q.db.QueryRowContext(ctx, getTurn, id)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Number,
		&i.Status,
		&i.FirstEventSeq,
		&i.LastEventSeq,
		&i.AssistantMsgID,
		&i.UsageID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertTurn = `-- name: InsertTurn :one
INSERT INTO turns (
    id, run_id, number, status, first_event_seq, last_event_seq, assistant_msg_id, usage_id, started_at, finished_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, run_id, number, status, first_event_seq, last_event_seq, assistant_msg_id, usage_id, started_at, finished_at
`

type InsertTurnParams struct {
	ID             string
	RunID          string
	Number         int64
	Status         string
	FirstEventSeq  int64
	LastEventSeq   int64
	AssistantMsgID sql.NullString
	UsageID        sql.NullString
	StartedAt      sql.NullString
	FinishedAt     sql.NullString
}

func (q *Queries) InsertTurn(ctx context.Context, arg InsertTurnParams) (Turn, error) {
	row := q.db.QueryRowContext(ctx, insertTurn,
		arg.ID,
		arg.RunID,
		arg.Number,
		arg.Status,
		arg.FirstEventSeq,
		arg.LastEventSeq,
		arg.AssistantMsgID,
		arg.UsageID,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Number,
		&i.Status,
		&i.FirstEventSeq,
		&i.LastEventSeq,
		&i.AssistantMsgID,
		&i.UsageID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listRunTurns = `-- name: ListRunTurns :many
SELECT id, run_id, number, status, first_event_seq, last_event_seq, assistant_msg_id, usage_id, started_at, finished_at FROM turns
WHERE run_id = ?
ORDER BY number
`

func (q *Queries) ListRunTurns(ctx context.Context, runID string) ([]Turn, error) {
	rows, err := q.db.QueryContext(ctx, listRunTurns, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Turn
	for rows.Next() {
		var i Turn
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Number,
			&i.Status,
			&i.FirstEventSeq,
			&i.LastEventSeq,
			&i.AssistantMsgID,
			&i.UsageID,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTurn = `-- name: UpdateTurn :one
UPDATE turns
SET status = ?, first_event_seq = ?, last_event_seq = ?, assistant_msg_id = ?, usage_id = ?, started_at = ?, finished_at = ?
WHERE id = ?
RETURNING id, run_id, number, status, first_event_seq, last_event_seq, assistant_msg_id, usage_id, started_at, finished_at
`

type UpdateTurnParams struct {
	Status         string
	FirstEventSeq  int64
	LastEventSeq   int64
	AssistantMsgID sql.NullString
	UsageID        sql.NullString
	StartedAt      sql.NullString
	FinishedAt     sql.NullString
	ID             string
}

func (q *Queries) UpdateTurn(ctx context.Context, arg UpdateTurnParams) (Turn, error) {
	row := q.db.QueryRowContext(ctx, updateTurn,
		arg.Status,
		arg.FirstEventSeq,
		arg.LastEventSeq,
		arg.AssistantMsgID,
		arg.UsageID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Number,
		&i.Status,
		&i.FirstEventSeq,
		&i.LastEventSeq,
		&i.AssistantMsgID,
		&i.UsageID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
