// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_records.sql

package sqlite

import (
	"context"
	"database/sql"
)

const countUsageByRun = `-- name: CountUsageByRun :one
SELECT COUNT(*) FROM usage_records
WHERE run_id = ?
`

func (q *Queries) CountUsageByRun(ctx context.Context, runID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsageByRun, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsageBySession = `-- name: CountUsageBySession :one
SELECT COUNT(*) FROM usage_records
WHERE session_id = ?
`

func (q *Queries) CountUsageBySession(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsageBySession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUsageRecord = `-- name: GetUsageRecord :one
SELECT id, session_id, run_id, turn_id, request_id, provider, model, usage_type, cache_creation_input_tokens, cache_read_input_tokens, output_tokens, reasoning_tokens, total_tokens, estimated, raw_provider_usage, created_at FROM usage_records
WHERE id = ?
`

func (q *Queries) GetUsageRecord(ctx context.Context, id string) (UsageRecord, error) {
	row := q.db.QueryRowContext(ctx, getUsageRecord, id)
	var i UsageRecord
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RunID,
		&i.TurnID,
		&i.RequestID,
		&i.Provider,
		&i.Model,
		&i.UsageType,
		&i.CacheCreationInputTokens,
		&i.CacheReadInputTokens,
		&i.OutputTokens,
		&i.ReasoningTokens,
		&i.TotalTokens,
		&i.Estimated,
		&i.RawProviderUsage,
		&i.CreatedAt,
	)
	return i, err
}

const insertUsageRecord = `-- name: InsertUsageRecord :one
INSERT INTO usage_records (
    id, session_id, run_id, turn_id, request_id, provider, model, usage_type,
    cache_creation_input_tokens, cache_read_input_tokens, output_tokens, reasoning_tokens, total_tokens,
    estimated, raw_provider_usage, created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, session_id, run_id, turn_id, request_id, provider, model, usage_type, cache_creation_input_tokens, cache_read_input_tokens, output_tokens, reasoning_tokens, total_tokens, estimated, raw_provider_usage, created_at
`

type InsertUsageRecordParams struct {
	ID                       string
	SessionID                string
	RunID                    string
	TurnID                   string
	RequestID                string
	Provider                 string
	Model                    string
	UsageType                string
	CacheCreationInputTokens int64
	CacheReadInputTokens     int64
	OutputTokens             int64
	ReasoningTokens          int64
	TotalTokens              int64
	Estimated                int64
	RawProviderUsage         sql.NullString
	CreatedAt                string
}

func (q *Queries) InsertUsageRecord(ctx context.Context, arg InsertUsageRecordParams) (UsageRecord, error) {
	row := q.db.QueryRowContext(ctx, insertUsageRecord,
		arg.ID,
		arg.SessionID,
		arg.RunID,
		arg.TurnID,
		arg.RequestID,
		arg.Provider,
		arg.Model,
		arg.UsageType,
		arg.CacheCreationInputTokens,
		arg.CacheReadInputTokens,
		arg.OutputTokens,
		arg.ReasoningTokens,
		arg.TotalTokens,
		arg.Estimated,
		arg.RawProviderUsage,
		arg.CreatedAt,
	)
	var i UsageRecord
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RunID,
		&i.TurnID,
		&i.RequestID,
		&i.Provider,
		&i.Model,
		&i.UsageType,
		&i.CacheCreationInputTokens,
		&i.CacheReadInputTokens,
		&i.OutputTokens,
		&i.ReasoningTokens,
		&i.TotalTokens,
		&i.Estimated,
		&i.RawProviderUsage,
		&i.CreatedAt,
	)
	return i, err
}
