// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: plugin.proto

package pluginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type BootstrapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostServerId  uint32                 `protobuf:"varint,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapRequest) Reset() {
	*x = BootstrapRequest{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapRequest) ProtoMessage() {}

func (x *BootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapRequest.ProtoReflect.Descriptor instead.
func (*BootstrapRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *BootstrapRequest) GetHostServerId() uint32 {
	if x != nil {
		return x.HostServerId
	}
	return 0
}

type Manifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subscriptions []string               `protobuf:"bytes,2,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Manifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manifest) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Seen          []string               `protobuf:"bytes,3,rep,name=seen,proto3" json:"seen,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId         string                 `protobuf:"bytes,5,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TurnId        string                 `protobuf:"bytes,6,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	Context       []byte                 `protobuf:"bytes,8,opt,name=context,proto3" json:"context,omitempty"` // 插件共享袋子，JSON object；不进模型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *Envelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Envelope) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *Envelope) GetSeen() []string {
	if x != nil {
		return x.Seen
	}
	return nil
}

func (x *Envelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Envelope) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Envelope) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

type Method struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Prompt           string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ParametersSchema []byte                 `protobuf:"bytes,3,opt,name=parameters_schema,json=parametersSchema,proto3" json:"parameters_schema,omitempty"`
	Capabilities     []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	RequiresApproval bool                   `protobuf:"varint,5,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Method) Reset() {
	*x = Method{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Method) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Method) ProtoMessage() {}

func (x *Method) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Method.ProtoReflect.Descriptor instead.
func (*Method) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *Method) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Method) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Method) GetParametersSchema() []byte {
	if x != nil {
		return x.ParametersSchema
	}
	return nil
}

func (x *Method) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Method) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

type MethodInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TurnId        string                 `protobuf:"bytes,3,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	CallId        string                 `protobuf:"bytes,4,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     []byte                 `protobuf:"bytes,6,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodInput) Reset() {
	*x = MethodInput{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodInput) ProtoMessage() {}

func (x *MethodInput) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodInput.ProtoReflect.Descriptor instead.
func (*MethodInput) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *MethodInput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MethodInput) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *MethodInput) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *MethodInput) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *MethodInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MethodInput) GetArguments() []byte {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type MethodResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output        []byte                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodResult) Reset() {
	*x = MethodResult{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodResult) ProtoMessage() {}

func (x *MethodResult) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodResult.ProtoReflect.Descriptor instead.
func (*MethodResult) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *MethodResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MethodResult) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *MethodResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MemoryKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryKey) Reset() {
	*x = MemoryKey{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryKey) ProtoMessage() {}

func (x *MemoryKey) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryKey.ProtoReflect.Descriptor instead.
func (*MemoryKey) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *MemoryKey) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MemoryKey) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *MemoryKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MemoryValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryValue) Reset() {
	*x = MemoryValue{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryValue) ProtoMessage() {}

func (x *MemoryValue) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryValue.ProtoReflect.Descriptor instead.
func (*MemoryValue) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *MemoryValue) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type MemoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *MemoryKey             `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryEntry) Reset() {
	*x = MemoryEntry{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryEntry) ProtoMessage() {}

func (x *MemoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryEntry.ProtoReflect.Descriptor instead.
func (*MemoryEntry) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *MemoryEntry) GetKey() *MemoryKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MemoryEntry) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *CompleteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CompleteRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CompleteRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CompleteRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CompleteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResult) Reset() {
	*x = CompleteResult{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResult) ProtoMessage() {}

func (x *CompleteResult) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResult.ProtoReflect.Descriptor instead.
func (*CompleteResult) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *CompleteResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Notice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notice) Reset() {
	*x = Notice{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notice) ProtoMessage() {}

func (x *Notice) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notice.ProtoReflect.Descriptor instead.
func (*Notice) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *Notice) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Notice) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Notice) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x12codedock.plugin.v1\"\a\n" +
	"\x05Empty\"8\n" +
	"\x10BootstrapRequest\x12$\n" +
	"\x0ehost_server_id\x18\x01 \x01(\rR\fhostServerId\"D\n" +
	"\bManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12$\n" +
	"\rsubscriptions\x18\x02 \x03(\tR\rsubscriptions\"\xd0\x01\n" +
	"\bEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12\x12\n" +
	"\x04seen\x18\x03 \x03(\tR\x04seen\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\x05 \x01(\tR\x05runId\x12\x17\n" +
	"\aturn_id\x18\x06 \x01(\tR\x06turnId\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12\x18\n" +
	"\acontext\x18\b \x01(\fR\acontext\"\xb2\x01\n" +
	"\x06Method\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12+\n" +
	"\x11parameters_schema\x18\x03 \x01(\fR\x10parametersSchema\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12+\n" +
	"\x11requires_approval\x18\x05 \x01(\bR\x10requiresApproval\"\xa7\x01\n" +
	"\vMethodInput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x17\n" +
	"\aturn_id\x18\x03 \x01(\tR\x06turnId\x12\x17\n" +
	"\acall_id\x18\x04 \x01(\tR\x06callId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x06 \x01(\fR\targuments\"V\n" +
	"\fMethodResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"T\n" +
	"\tMemoryKey\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"!\n" +
	"\vMemoryValue\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"R\n" +
	"\vMemoryEntry\x12/\n" +
	"\x03key\x18\x01 \x01(\v2\x1d.codedock.plugin.v1.MemoryKeyR\x03key\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"s\n" +
	"\x0fCompleteRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"$\n" +
	"\x0eCompleteResult\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"R\n" +
	"\x06Notice\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text2\xf4\x01\n" +
	"\x06Plugin\x12O\n" +
	"\tBootstrap\x12$.codedock.plugin.v1.BootstrapRequest\x1a\x1c.codedock.plugin.v1.Manifest\x12E\n" +
	"\aOnEvent\x12\x1c.codedock.plugin.v1.Envelope\x1a\x1c.codedock.plugin.v1.Envelope\x12R\n" +
	"\rExecuteMethod\x12\x1f.codedock.plugin.v1.MethodInput\x1a .codedock.plugin.v1.MethodResult2\xc5\x03\n" +
	"\x04Host\x12?\n" +
	"\x04Emit\x12\x1c.codedock.plugin.v1.Envelope\x1a\x19.codedock.plugin.v1.Empty\x12G\n" +
	"\x0eRegisterMethod\x12\x1a.codedock.plugin.v1.Method\x1a\x19.codedock.plugin.v1.Empty\x12K\n" +
	"\tMemoryGet\x12\x1d.codedock.plugin.v1.MemoryKey\x1a\x1f.codedock.plugin.v1.MemoryValue\x12J\n" +
	"\fMemoryUpsert\x12\x1f.codedock.plugin.v1.MemoryEntry\x1a\x19.codedock.plugin.v1.Empty\x12S\n" +
	"\bComplete\x12#.codedock.plugin.v1.CompleteRequest\x1a\".codedock.plugin.v1.CompleteResult\x12E\n" +
	"\fAppendNotice\x12\x1a.codedock.plugin.v1.Notice\x1a\x19.codedock.plugin.v1.EmptyB$Z\"codedock/pkg/plugin/proto;pluginpbb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_plugin_proto_goTypes = []any{
	(*Empty)(nil),            // 0: codedock.plugin.v1.Empty
	(*BootstrapRequest)(nil), // 1: codedock.plugin.v1.BootstrapRequest
	(*Manifest)(nil),         // 2: codedock.plugin.v1.Manifest
	(*Envelope)(nil),         // 3: codedock.plugin.v1.Envelope
	(*Method)(nil),           // 4: codedock.plugin.v1.Method
	(*MethodInput)(nil),      // 5: codedock.plugin.v1.MethodInput
	(*MethodResult)(nil),     // 6: codedock.plugin.v1.MethodResult
	(*MemoryKey)(nil),        // 7: codedock.plugin.v1.MemoryKey
	(*MemoryValue)(nil),      // 8: codedock.plugin.v1.MemoryValue
	(*MemoryEntry)(nil),      // 9: codedock.plugin.v1.MemoryEntry
	(*CompleteRequest)(nil),  // 10: codedock.plugin.v1.CompleteRequest
	(*CompleteResult)(nil),   // 11: codedock.plugin.v1.CompleteResult
	(*Notice)(nil),           // 12: codedock.plugin.v1.Notice
}
var file_plugin_proto_depIdxs = []int32{
	7,  // 0: codedock.plugin.v1.MemoryEntry.key:type_name -> codedock.plugin.v1.MemoryKey
	1,  // 1: codedock.plugin.v1.Plugin.Bootstrap:input_type -> codedock.plugin.v1.BootstrapRequest
	3,  // 2: codedock.plugin.v1.Plugin.OnEvent:input_type -> codedock.plugin.v1.Envelope
	5,  // 3: codedock.plugin.v1.Plugin.ExecuteMethod:input_type -> codedock.plugin.v1.MethodInput
	3,  // 4: codedock.plugin.v1.Host.Emit:input_type -> codedock.plugin.v1.Envelope
	4,  // 5: codedock.plugin.v1.Host.RegisterMethod:input_type -> codedock.plugin.v1.Method
	7,  // 6: codedock.plugin.v1.Host.MemoryGet:input_type -> codedock.plugin.v1.MemoryKey
	9,  // 7: codedock.plugin.v1.Host.MemoryUpsert:input_type -> codedock.plugin.v1.MemoryEntry
	10, // 8: codedock.plugin.v1.Host.Complete:input_type -> codedock.plugin.v1.CompleteRequest
	12, // 9: codedock.plugin.v1.Host.AppendNotice:input_type -> codedock.plugin.v1.Notice
	2,  // 10: codedock.plugin.v1.Plugin.Bootstrap:output_type -> codedock.plugin.v1.Manifest
	3,  // 11: codedock.plugin.v1.Plugin.OnEvent:output_type -> codedock.plugin.v1.Envelope
	6,  // 12: codedock.plugin.v1.Plugin.ExecuteMethod:output_type -> codedock.plugin.v1.MethodResult
	0,  // 13: codedock.plugin.v1.Host.Emit:output_type -> codedock.plugin.v1.Empty
	0,  // 14: codedock.plugin.v1.Host.RegisterMethod:output_type -> codedock.plugin.v1.Empty
	8,  // 15: codedock.plugin.v1.Host.MemoryGet:output_type -> codedock.plugin.v1.MemoryValue
	0,  // 16: codedock.plugin.v1.Host.MemoryUpsert:output_type -> codedock.plugin.v1.Empty
	11, // 17: codedock.plugin.v1.Host.Complete:output_type -> codedock.plugin.v1.CompleteResult
	0,  // 18: codedock.plugin.v1.Host.AppendNotice:output_type -> codedock.plugin.v1.Empty
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
